version: "3"

services:
  app:
    build:
      context: .

    command: sh -c "make test"

    links:
      - mysql
      - postgresql

    environment:
      # TEST_ARGS: -v
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: plant_erd_test
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: plant_erd_test

    volumes:
      - go-mod:/go/pkg/mod

  mysql:
    image: mysql:8

    ports:
      - 3306:3306

    environment:
      MYSQL_DATABASE: plant_erd_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"

  postgresql:
    image: postgres:12-alpine

    ports:
      - 5432:5432

    environment:
      POSTGRES_DB: plant_erd_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  go-mod:
    driver: local
