name: Build
on:
  push:
    branches:
      - "**/*"
    tags:
      - "v*"

env:
  GO111MODULE: "on"

jobs:
  gox:
    name: gox

    strategy:
      fail-fast: false
      matrix:
        artifact_key:
          - darwin
          - freebsd
          - linux_1
          - linux_2
          - netbsd
          - openbsd
          - windows
        include:
          - artifact_key: darwin
            os: macos-latest
            osarch: darwin/386 darwin/amd64
          - artifact_key: freebsd
            os: ubuntu-latest
            osarch: freebsd/386 freebsd/amd64 freebsd/arm
          - artifact_key: linux_1
            os: ubuntu-latest
            osarch: linux/386 linux/amd64 linux/arm linux/s390x
          - artifact_key: linux_2
            os: ubuntu-latest
            osarch: linux/mips64 linux/mips64le linux/mips linux/mipsle
          - artifact_key: netbsd
            os: ubuntu-latest
            osarch: netbsd/amd64 netbsd/arm netbsd/386
          - artifact_key: openbsd
            os: ubuntu-latest
            osarch: openbsd/386 openbsd/amd64
          - artifact_key: windows
            os: ubuntu-latest
            osarch: windows/amd64 windows/386

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: make package
        run: |
          set -xe

          export GOPATH=`go env GOPATH`
          export PATH=$GOPATH/bin:$PATH

          go get -u github.com/mitchellh/gox
          make clean gox_with_zip

        env:
          GOX_OSARCH: ${{ matrix.osarch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: bin-${{ matrix.artifact_key }}
          path: bin/

      - name: Slack Notification (not success)
        uses: homoluctus/slatify@v2.0.0
        if: "! success()"
        with:
          job_name: '*build*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release

    needs:
      - gox

    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts from darwin
        uses: actions/download-artifact@v1
        with:
          name: bin-darwin
          path: bin/

      - name: Download artifacts from freebsd
        uses: actions/download-artifact@v1
        with:
          name: bin-freebsd
          path: bin/

      - name: Download artifacts from linux_1
        uses: actions/download-artifact@v1
        with:
          name: bin-linux_1
          path: bin/

      - name: Download artifacts from linux_2
        uses: actions/download-artifact@v1
        with:
          name: bin-linux_2
          path: bin/

      - name: Download artifacts from netbsd
        uses: actions/download-artifact@v1
        with:
          name: bin-netbsd
          path: bin/

      - name: Download artifacts from openbsd
        uses: actions/download-artifact@v1
        with:
          name: bin-openbsd
          path: bin/

      - name: Download artifacts from windows
        uses: actions/download-artifact@v1
        with:
          name: bin-windows
          path: bin/

      - name: Upload to GitHub Releases
        run: |
          set -xe

          export GOPATH=`go env GOPATH`
          export PATH=$GOPATH/bin:$PATH

          export PUSH_EVENT_REF=$(jq --raw-output .ref "$GITHUB_EVENT_PATH")

          if [ "$(echo $PUSH_EVENT_REF | grep refs/tags/ | wc -l)" = "0" ]; then
            echo "ref is not a tag: ${PUSH_EVENT_REF}"
            exit 1
          fi

          export TAGNAME=$(echo $PUSH_EVENT_REF | sed -e 's!refs/tags/!!g')
          export USERNAME=$(echo $GITHUB_REPOSITORY | cut -d / -f 1)
          export REPO=$(echo $GITHUB_REPOSITORY | cut -d / -f 2)

          go get -u github.com/tcnksm/ghr
          $GOPATH/bin/ghr -u ${USERNAME} -r ${REPO} -n ${TAGNAME} -b "Release ${TAGNAME}" ${TAGNAME} bin/

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')

      - name: Slack Notification
        uses: homoluctus/slatify@v2.0.0
        if: always()
        with:
          job_name: '*release*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}
